---

# This playbook joins a linux server (debian/ubunto) to an active directory domain.

- name: Apply common configuration
  hosts: domain_join
  become: true

  roles:
    - common

- name: Apply configuration to newly deployed machines
  hosts: domain_join
  become: true

  roles:
   - domain_join
