---
# Common features for all linux servers

- name: Install ntp
  apt:
    name: ntp
    state: present
  tags: ntp

- name: Configure ntp file
  template:
    src: ntp.conf.t1
    dest: /etc/ntp.conf
    backup: yes
  tags: ntp
  notify: restart ntp
  become: true

- name: Start the ntp service
  service:
    name: ntp
    state: started
    enabled: yes
  tags: ntp
