---
# Common features for all linux servers

- name: Install ntp
  apt:
    name: ntp
    state: present
  tags: ntp



- name: Start the ntp service
  service:
    name: ntp
    state: started
    enabled: yes
  tags: ntp
